//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlatformAdminSite.PlatformInitializationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataAccessResponseType", Namespace="http://schemas.datacontract.org/2004/07/Sahara.Core.Common.ResponseTypes")]
    [System.SerializableAttribute()]
    public partial class DataAccessResponseType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ErrorMessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoleInstanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuccessCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuccessMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] SuccessMessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isSuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ErrorMessages {
            get {
                return this.ErrorMessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessagesField, value) != true)) {
                    this.ErrorMessagesField = value;
                    this.RaisePropertyChanged("ErrorMessages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Results {
            get {
                return this.ResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultsField, value) != true)) {
                    this.ResultsField = value;
                    this.RaisePropertyChanged("Results");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoleInstance {
            get {
                return this.RoleInstanceField;
            }
            set {
                if ((this.RoleInstanceField.Equals(value) != true)) {
                    this.RoleInstanceField = value;
                    this.RaisePropertyChanged("RoleInstance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleName {
            get {
                return this.RoleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleNameField, value) != true)) {
                    this.RoleNameField = value;
                    this.RaisePropertyChanged("RoleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SuccessCode {
            get {
                return this.SuccessCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SuccessCodeField, value) != true)) {
                    this.SuccessCodeField = value;
                    this.RaisePropertyChanged("SuccessCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SuccessMessage {
            get {
                return this.SuccessMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.SuccessMessageField, value) != true)) {
                    this.SuccessMessageField = value;
                    this.RaisePropertyChanged("SuccessMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] SuccessMessages {
            get {
                return this.SuccessMessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.SuccessMessagesField, value) != true)) {
                    this.SuccessMessagesField = value;
                    this.RaisePropertyChanged("SuccessMessages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isSuccess {
            get {
                return this.isSuccessField;
            }
            set {
                if ((this.isSuccessField.Equals(value) != true)) {
                    this.isSuccessField = value;
                    this.RaisePropertyChanged("isSuccess");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PlatformInitializationService.IPlatformInitializationService")]
    public interface IPlatformInitializationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlatformInitializationService/IsPlatformInitialized", ReplyAction="http://tempuri.org/IPlatformInitializationService/IsPlatformInitializedResponse")]
        bool IsPlatformInitialized();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlatformInitializationService/IsPlatformInitialized", ReplyAction="http://tempuri.org/IPlatformInitializationService/IsPlatformInitializedResponse")]
        System.Threading.Tasks.Task<bool> IsPlatformInitializedAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlatformInitializationService/ProvisionPlatform", ReplyAction="http://tempuri.org/IPlatformInitializationService/ProvisionPlatformResponse")]
        PlatformAdminSite.PlatformInitializationService.DataAccessResponseType ProvisionPlatform(string FirstName, string LastName, string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlatformInitializationService/ProvisionPlatform", ReplyAction="http://tempuri.org/IPlatformInitializationService/ProvisionPlatformResponse")]
        System.Threading.Tasks.Task<PlatformAdminSite.PlatformInitializationService.DataAccessResponseType> ProvisionPlatformAsync(string FirstName, string LastName, string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlatformInitializationService/PurgePlatform", ReplyAction="http://tempuri.org/IPlatformInitializationService/PurgePlatformResponse")]
        PlatformAdminSite.PlatformInitializationService.DataAccessResponseType PurgePlatform();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlatformInitializationService/PurgePlatform", ReplyAction="http://tempuri.org/IPlatformInitializationService/PurgePlatformResponse")]
        System.Threading.Tasks.Task<PlatformAdminSite.PlatformInitializationService.DataAccessResponseType> PurgePlatformAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPlatformInitializationServiceChannel : PlatformAdminSite.PlatformInitializationService.IPlatformInitializationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlatformInitializationServiceClient : System.ServiceModel.ClientBase<PlatformAdminSite.PlatformInitializationService.IPlatformInitializationService>, PlatformAdminSite.PlatformInitializationService.IPlatformInitializationService {
        
        public PlatformInitializationServiceClient() {
        }
        
        public PlatformInitializationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlatformInitializationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlatformInitializationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlatformInitializationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool IsPlatformInitialized() {
            return base.Channel.IsPlatformInitialized();
        }
        
        public System.Threading.Tasks.Task<bool> IsPlatformInitializedAsync() {
            return base.Channel.IsPlatformInitializedAsync();
        }
        
        public PlatformAdminSite.PlatformInitializationService.DataAccessResponseType ProvisionPlatform(string FirstName, string LastName, string Email, string Password) {
            return base.Channel.ProvisionPlatform(FirstName, LastName, Email, Password);
        }
        
        public System.Threading.Tasks.Task<PlatformAdminSite.PlatformInitializationService.DataAccessResponseType> ProvisionPlatformAsync(string FirstName, string LastName, string Email, string Password) {
            return base.Channel.ProvisionPlatformAsync(FirstName, LastName, Email, Password);
        }
        
        public PlatformAdminSite.PlatformInitializationService.DataAccessResponseType PurgePlatform() {
            return base.Channel.PurgePlatform();
        }
        
        public System.Threading.Tasks.Task<PlatformAdminSite.PlatformInitializationService.DataAccessResponseType> PurgePlatformAsync() {
            return base.Channel.PurgePlatformAsync();
        }
    }
}
