//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlatformAdminSite.PlatformSettingsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CorePlatformSettings", Namespace="http://schemas.datacontract.org/2004/07/WCF.WcfEndpoints.Contracts.Platform")]
    [System.SerializableAttribute()]
    public partial class CorePlatformSettings : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PlatformAdminSite.PlatformSettingsService.CorePlatformSettings.AccountSettings AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PlatformAdminSite.PlatformSettingsService.CorePlatformSettings.CustodianSettings CustodianField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PlatformAdminSite.PlatformSettingsService.CorePlatformSettings.CustomDomain[] CustomDomainsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PlatformAdminSite.PlatformSettingsService.CorePlatformSettings.DocumentDBCredentials DocumentDBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PlatformAdminSite.PlatformSettingsService.CorePlatformSettings.EnvironmentSettings EnvironmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GoogleMapsAPIKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PlatformAdminSite.PlatformSettingsService.CorePlatformSettings.RedisConfigurations RedisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PlatformAdminSite.PlatformSettingsService.CorePlatformSettings.RegsitrationSettings RegistrationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PlatformAdminSite.PlatformSettingsService.SearchPartition[] SearchParitionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PlatformAdminSite.PlatformSettingsService.CorePlatformSettings.SendGridCredentials SendGridField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PlatformAdminSite.PlatformSettingsService.CorePlatformSettings.StorageCredentials StorageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PlatformAdminSite.PlatformSettingsService.StoragePartition[] StorageParitionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PlatformAdminSite.PlatformSettingsService.CorePlatformSettings.URLSettings UrlsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PlatformAdminSite.PlatformSettingsService.CorePlatformSettings.WorkerSettings WorkerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PlatformAdminSite.PlatformSettingsService.CorePlatformSettings.AccountSettings Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationName {
            get {
                return this.ApplicationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationNameField, value) != true)) {
                    this.ApplicationNameField = value;
                    this.RaisePropertyChanged("ApplicationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PlatformAdminSite.PlatformSettingsService.CorePlatformSettings.CustodianSettings Custodian {
            get {
                return this.CustodianField;
            }
            set {
                if ((object.ReferenceEquals(this.CustodianField, value) != true)) {
                    this.CustodianField = value;
                    this.RaisePropertyChanged("Custodian");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PlatformAdminSite.PlatformSettingsService.CorePlatformSettings.CustomDomain[] CustomDomains {
            get {
                return this.CustomDomainsField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomDomainsField, value) != true)) {
                    this.CustomDomainsField = value;
                    this.RaisePropertyChanged("CustomDomains");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PlatformAdminSite.PlatformSettingsService.CorePlatformSettings.DocumentDBCredentials DocumentDB {
            get {
                return this.DocumentDBField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentDBField, value) != true)) {
                    this.DocumentDBField = value;
                    this.RaisePropertyChanged("DocumentDB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PlatformAdminSite.PlatformSettingsService.CorePlatformSettings.EnvironmentSettings Environment {
            get {
                return this.EnvironmentField;
            }
            set {
                if ((object.ReferenceEquals(this.EnvironmentField, value) != true)) {
                    this.EnvironmentField = value;
                    this.RaisePropertyChanged("Environment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GoogleMapsAPIKey {
            get {
                return this.GoogleMapsAPIKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.GoogleMapsAPIKeyField, value) != true)) {
                    this.GoogleMapsAPIKeyField = value;
                    this.RaisePropertyChanged("GoogleMapsAPIKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PlatformAdminSite.PlatformSettingsService.CorePlatformSettings.RedisConfigurations Redis {
            get {
                return this.RedisField;
            }
            set {
                if ((object.ReferenceEquals(this.RedisField, value) != true)) {
                    this.RedisField = value;
                    this.RaisePropertyChanged("Redis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PlatformAdminSite.PlatformSettingsService.CorePlatformSettings.RegsitrationSettings Registration {
            get {
                return this.RegistrationField;
            }
            set {
                if ((object.ReferenceEquals(this.RegistrationField, value) != true)) {
                    this.RegistrationField = value;
                    this.RaisePropertyChanged("Registration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PlatformAdminSite.PlatformSettingsService.SearchPartition[] SearchParitions {
            get {
                return this.SearchParitionsField;
            }
            set {
                if ((object.ReferenceEquals(this.SearchParitionsField, value) != true)) {
                    this.SearchParitionsField = value;
                    this.RaisePropertyChanged("SearchParitions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PlatformAdminSite.PlatformSettingsService.CorePlatformSettings.SendGridCredentials SendGrid {
            get {
                return this.SendGridField;
            }
            set {
                if ((object.ReferenceEquals(this.SendGridField, value) != true)) {
                    this.SendGridField = value;
                    this.RaisePropertyChanged("SendGrid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PlatformAdminSite.PlatformSettingsService.CorePlatformSettings.StorageCredentials Storage {
            get {
                return this.StorageField;
            }
            set {
                if ((object.ReferenceEquals(this.StorageField, value) != true)) {
                    this.StorageField = value;
                    this.RaisePropertyChanged("Storage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PlatformAdminSite.PlatformSettingsService.StoragePartition[] StorageParitions {
            get {
                return this.StorageParitionsField;
            }
            set {
                if ((object.ReferenceEquals(this.StorageParitionsField, value) != true)) {
                    this.StorageParitionsField = value;
                    this.RaisePropertyChanged("StorageParitions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PlatformAdminSite.PlatformSettingsService.CorePlatformSettings.URLSettings Urls {
            get {
                return this.UrlsField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlsField, value) != true)) {
                    this.UrlsField = value;
                    this.RaisePropertyChanged("Urls");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PlatformAdminSite.PlatformSettingsService.CorePlatformSettings.WorkerSettings Worker {
            get {
                return this.WorkerField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkerField, value) != true)) {
                    this.WorkerField = value;
                    this.RaisePropertyChanged("Worker");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="CorePlatformSettings.AccountSettings", Namespace="http://schemas.datacontract.org/2004/07/WCF.WcfEndpoints.Contracts.Platform")]
        [System.SerializableAttribute()]
        public partial class AccountSettings : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private int TrialLengthField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public int TrialLength {
                get {
                    return this.TrialLengthField;
                }
                set {
                    if ((this.TrialLengthField.Equals(value) != true)) {
                        this.TrialLengthField = value;
                        this.RaisePropertyChanged("TrialLength");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="CorePlatformSettings.CustodianSettings", Namespace="http://schemas.datacontract.org/2004/07/WCF.WcfEndpoints.Contracts.Platform")]
        [System.SerializableAttribute()]
        public partial class CustodianSettings : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string CustodianFrequencyDescriptionField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private int CustodianFrequencyMillisecondsField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string CustodianFrequencyDescription {
                get {
                    return this.CustodianFrequencyDescriptionField;
                }
                set {
                    if ((object.ReferenceEquals(this.CustodianFrequencyDescriptionField, value) != true)) {
                        this.CustodianFrequencyDescriptionField = value;
                        this.RaisePropertyChanged("CustodianFrequencyDescription");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public int CustodianFrequencyMilliseconds {
                get {
                    return this.CustodianFrequencyMillisecondsField;
                }
                set {
                    if ((this.CustodianFrequencyMillisecondsField.Equals(value) != true)) {
                        this.CustodianFrequencyMillisecondsField = value;
                        this.RaisePropertyChanged("CustodianFrequencyMilliseconds");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="CorePlatformSettings.DocumentDBCredentials", Namespace="http://schemas.datacontract.org/2004/07/WCF.WcfEndpoints.Contracts.Platform")]
        [System.SerializableAttribute()]
        public partial class DocumentDBCredentials : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string AccountPartitionsDatabaseIdField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string AccountPartitionsReadOnlyAccountKeyField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string AccountPartitionsReadOnlyAccountNameField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string AccountPartitionsDatabaseId {
                get {
                    return this.AccountPartitionsDatabaseIdField;
                }
                set {
                    if ((object.ReferenceEquals(this.AccountPartitionsDatabaseIdField, value) != true)) {
                        this.AccountPartitionsDatabaseIdField = value;
                        this.RaisePropertyChanged("AccountPartitionsDatabaseId");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string AccountPartitionsReadOnlyAccountKey {
                get {
                    return this.AccountPartitionsReadOnlyAccountKeyField;
                }
                set {
                    if ((object.ReferenceEquals(this.AccountPartitionsReadOnlyAccountKeyField, value) != true)) {
                        this.AccountPartitionsReadOnlyAccountKeyField = value;
                        this.RaisePropertyChanged("AccountPartitionsReadOnlyAccountKey");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string AccountPartitionsReadOnlyAccountName {
                get {
                    return this.AccountPartitionsReadOnlyAccountNameField;
                }
                set {
                    if ((object.ReferenceEquals(this.AccountPartitionsReadOnlyAccountNameField, value) != true)) {
                        this.AccountPartitionsReadOnlyAccountNameField = value;
                        this.RaisePropertyChanged("AccountPartitionsReadOnlyAccountName");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="CorePlatformSettings.EnvironmentSettings", Namespace="http://schemas.datacontract.org/2004/07/WCF.WcfEndpoints.Contracts.Platform")]
        [System.SerializableAttribute()]
        public partial class EnvironmentSettings : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string CurrentField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Current {
                get {
                    return this.CurrentField;
                }
                set {
                    if ((object.ReferenceEquals(this.CurrentField, value) != true)) {
                        this.CurrentField = value;
                        this.RaisePropertyChanged("Current");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="CorePlatformSettings.RedisConfigurations", Namespace="http://schemas.datacontract.org/2004/07/WCF.WcfEndpoints.Contracts.Platform")]
        [System.SerializableAttribute()]
        public partial class RedisConfigurations : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string UnsecureField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Unsecure {
                get {
                    return this.UnsecureField;
                }
                set {
                    if ((object.ReferenceEquals(this.UnsecureField, value) != true)) {
                        this.UnsecureField = value;
                        this.RaisePropertyChanged("Unsecure");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="CorePlatformSettings.RegsitrationSettings", Namespace="http://schemas.datacontract.org/2004/07/WCF.WcfEndpoints.Contracts.Platform")]
        [System.SerializableAttribute()]
        public partial class RegsitrationSettings : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private int PasswordMinLengthField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public int PasswordMinLength {
                get {
                    return this.PasswordMinLengthField;
                }
                set {
                    if ((this.PasswordMinLengthField.Equals(value) != true)) {
                        this.PasswordMinLengthField = value;
                        this.RaisePropertyChanged("PasswordMinLength");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="CorePlatformSettings.SendGridCredentials", Namespace="http://schemas.datacontract.org/2004/07/WCF.WcfEndpoints.Contracts.Platform")]
        [System.SerializableAttribute()]
        public partial class SendGridCredentials : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string ApiKeyField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string ApiKey {
                get {
                    return this.ApiKeyField;
                }
                set {
                    if ((object.ReferenceEquals(this.ApiKeyField, value) != true)) {
                        this.ApiKeyField = value;
                        this.RaisePropertyChanged("ApiKey");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="CorePlatformSettings.StorageCredentials", Namespace="http://schemas.datacontract.org/2004/07/WCF.WcfEndpoints.Contracts.Platform")]
        [System.SerializableAttribute()]
        public partial class StorageCredentials : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string IntermediaryKeyField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string IntermediaryNameField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string IntermediaryKey {
                get {
                    return this.IntermediaryKeyField;
                }
                set {
                    if ((object.ReferenceEquals(this.IntermediaryKeyField, value) != true)) {
                        this.IntermediaryKeyField = value;
                        this.RaisePropertyChanged("IntermediaryKey");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string IntermediaryName {
                get {
                    return this.IntermediaryNameField;
                }
                set {
                    if ((object.ReferenceEquals(this.IntermediaryNameField, value) != true)) {
                        this.IntermediaryNameField = value;
                        this.RaisePropertyChanged("IntermediaryName");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="CorePlatformSettings.URLSettings", Namespace="http://schemas.datacontract.org/2004/07/WCF.WcfEndpoints.Contracts.Platform")]
        [System.SerializableAttribute()]
        public partial class URLSettings : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string AboutUsUriField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string AcceptableUseField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string AccountManagementDomainField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string AccountServiceDomainField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string AccountSiteDomainField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string AccountUserAcceptInvitationUrlField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string AccountUserPasswordClaimUrlField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string ImagingApiEndpointField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string IntermediaryImagingBlobUriField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string IntermediaryImagingCdnUriField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string MasterDomainField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string PlatformImagingBlobUriField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string PlatformImagingCdnUriField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string PlatformUserAcceptInvitationUrlField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string PlatformUserPasswordClaimUrlField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string PrivacyPolicyUriField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string RegistrationApiEndpointField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string RegistrationEndpointField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string ServiceAgreementUriField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string TermsAndConditionsUriField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string AboutUsUri {
                get {
                    return this.AboutUsUriField;
                }
                set {
                    if ((object.ReferenceEquals(this.AboutUsUriField, value) != true)) {
                        this.AboutUsUriField = value;
                        this.RaisePropertyChanged("AboutUsUri");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string AcceptableUse {
                get {
                    return this.AcceptableUseField;
                }
                set {
                    if ((object.ReferenceEquals(this.AcceptableUseField, value) != true)) {
                        this.AcceptableUseField = value;
                        this.RaisePropertyChanged("AcceptableUse");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string AccountManagementDomain {
                get {
                    return this.AccountManagementDomainField;
                }
                set {
                    if ((object.ReferenceEquals(this.AccountManagementDomainField, value) != true)) {
                        this.AccountManagementDomainField = value;
                        this.RaisePropertyChanged("AccountManagementDomain");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string AccountServiceDomain {
                get {
                    return this.AccountServiceDomainField;
                }
                set {
                    if ((object.ReferenceEquals(this.AccountServiceDomainField, value) != true)) {
                        this.AccountServiceDomainField = value;
                        this.RaisePropertyChanged("AccountServiceDomain");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string AccountSiteDomain {
                get {
                    return this.AccountSiteDomainField;
                }
                set {
                    if ((object.ReferenceEquals(this.AccountSiteDomainField, value) != true)) {
                        this.AccountSiteDomainField = value;
                        this.RaisePropertyChanged("AccountSiteDomain");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string AccountUserAcceptInvitationUrl {
                get {
                    return this.AccountUserAcceptInvitationUrlField;
                }
                set {
                    if ((object.ReferenceEquals(this.AccountUserAcceptInvitationUrlField, value) != true)) {
                        this.AccountUserAcceptInvitationUrlField = value;
                        this.RaisePropertyChanged("AccountUserAcceptInvitationUrl");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string AccountUserPasswordClaimUrl {
                get {
                    return this.AccountUserPasswordClaimUrlField;
                }
                set {
                    if ((object.ReferenceEquals(this.AccountUserPasswordClaimUrlField, value) != true)) {
                        this.AccountUserPasswordClaimUrlField = value;
                        this.RaisePropertyChanged("AccountUserPasswordClaimUrl");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string ImagingApiEndpoint {
                get {
                    return this.ImagingApiEndpointField;
                }
                set {
                    if ((object.ReferenceEquals(this.ImagingApiEndpointField, value) != true)) {
                        this.ImagingApiEndpointField = value;
                        this.RaisePropertyChanged("ImagingApiEndpoint");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string IntermediaryImagingBlobUri {
                get {
                    return this.IntermediaryImagingBlobUriField;
                }
                set {
                    if ((object.ReferenceEquals(this.IntermediaryImagingBlobUriField, value) != true)) {
                        this.IntermediaryImagingBlobUriField = value;
                        this.RaisePropertyChanged("IntermediaryImagingBlobUri");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string IntermediaryImagingCdnUri {
                get {
                    return this.IntermediaryImagingCdnUriField;
                }
                set {
                    if ((object.ReferenceEquals(this.IntermediaryImagingCdnUriField, value) != true)) {
                        this.IntermediaryImagingCdnUriField = value;
                        this.RaisePropertyChanged("IntermediaryImagingCdnUri");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string MasterDomain {
                get {
                    return this.MasterDomainField;
                }
                set {
                    if ((object.ReferenceEquals(this.MasterDomainField, value) != true)) {
                        this.MasterDomainField = value;
                        this.RaisePropertyChanged("MasterDomain");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string PlatformImagingBlobUri {
                get {
                    return this.PlatformImagingBlobUriField;
                }
                set {
                    if ((object.ReferenceEquals(this.PlatformImagingBlobUriField, value) != true)) {
                        this.PlatformImagingBlobUriField = value;
                        this.RaisePropertyChanged("PlatformImagingBlobUri");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string PlatformImagingCdnUri {
                get {
                    return this.PlatformImagingCdnUriField;
                }
                set {
                    if ((object.ReferenceEquals(this.PlatformImagingCdnUriField, value) != true)) {
                        this.PlatformImagingCdnUriField = value;
                        this.RaisePropertyChanged("PlatformImagingCdnUri");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string PlatformUserAcceptInvitationUrl {
                get {
                    return this.PlatformUserAcceptInvitationUrlField;
                }
                set {
                    if ((object.ReferenceEquals(this.PlatformUserAcceptInvitationUrlField, value) != true)) {
                        this.PlatformUserAcceptInvitationUrlField = value;
                        this.RaisePropertyChanged("PlatformUserAcceptInvitationUrl");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string PlatformUserPasswordClaimUrl {
                get {
                    return this.PlatformUserPasswordClaimUrlField;
                }
                set {
                    if ((object.ReferenceEquals(this.PlatformUserPasswordClaimUrlField, value) != true)) {
                        this.PlatformUserPasswordClaimUrlField = value;
                        this.RaisePropertyChanged("PlatformUserPasswordClaimUrl");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string PrivacyPolicyUri {
                get {
                    return this.PrivacyPolicyUriField;
                }
                set {
                    if ((object.ReferenceEquals(this.PrivacyPolicyUriField, value) != true)) {
                        this.PrivacyPolicyUriField = value;
                        this.RaisePropertyChanged("PrivacyPolicyUri");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string RegistrationApiEndpoint {
                get {
                    return this.RegistrationApiEndpointField;
                }
                set {
                    if ((object.ReferenceEquals(this.RegistrationApiEndpointField, value) != true)) {
                        this.RegistrationApiEndpointField = value;
                        this.RaisePropertyChanged("RegistrationApiEndpoint");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string RegistrationEndpoint {
                get {
                    return this.RegistrationEndpointField;
                }
                set {
                    if ((object.ReferenceEquals(this.RegistrationEndpointField, value) != true)) {
                        this.RegistrationEndpointField = value;
                        this.RaisePropertyChanged("RegistrationEndpoint");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string ServiceAgreementUri {
                get {
                    return this.ServiceAgreementUriField;
                }
                set {
                    if ((object.ReferenceEquals(this.ServiceAgreementUriField, value) != true)) {
                        this.ServiceAgreementUriField = value;
                        this.RaisePropertyChanged("ServiceAgreementUri");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string TermsAndConditionsUri {
                get {
                    return this.TermsAndConditionsUriField;
                }
                set {
                    if ((object.ReferenceEquals(this.TermsAndConditionsUriField, value) != true)) {
                        this.TermsAndConditionsUriField = value;
                        this.RaisePropertyChanged("TermsAndConditionsUri");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="CorePlatformSettings.WorkerSettings", Namespace="http://schemas.datacontract.org/2004/07/WCF.WcfEndpoints.Contracts.Platform")]
        [System.SerializableAttribute()]
        public partial class WorkerSettings : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string WorkerFrequencyDescriptionField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private int WorkerFrequencyMillisecondsField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string WorkerFrequencyDescription {
                get {
                    return this.WorkerFrequencyDescriptionField;
                }
                set {
                    if ((object.ReferenceEquals(this.WorkerFrequencyDescriptionField, value) != true)) {
                        this.WorkerFrequencyDescriptionField = value;
                        this.RaisePropertyChanged("WorkerFrequencyDescription");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public int WorkerFrequencyMilliseconds {
                get {
                    return this.WorkerFrequencyMillisecondsField;
                }
                set {
                    if ((this.WorkerFrequencyMillisecondsField.Equals(value) != true)) {
                        this.WorkerFrequencyMillisecondsField = value;
                        this.RaisePropertyChanged("WorkerFrequencyMilliseconds");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="CorePlatformSettings.CustomDomain", Namespace="http://schemas.datacontract.org/2004/07/WCF.WcfEndpoints.Contracts.Platform")]
        [System.SerializableAttribute()]
        public partial class CustomDomain : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string AccountNameKeyField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string DomainField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string AccountNameKey {
                get {
                    return this.AccountNameKeyField;
                }
                set {
                    if ((object.ReferenceEquals(this.AccountNameKeyField, value) != true)) {
                        this.AccountNameKeyField = value;
                        this.RaisePropertyChanged("AccountNameKey");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Domain {
                get {
                    return this.DomainField;
                }
                set {
                    if ((object.ReferenceEquals(this.DomainField, value) != true)) {
                        this.DomainField = value;
                        this.RaisePropertyChanged("Domain");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchPartition", Namespace="http://schemas.datacontract.org/2004/07/Sahara.Core.Settings.Models.Partitions")]
    [System.SerializableAttribute()]
    public partial class SearchPartition : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxTenantsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TenantCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxTenants {
            get {
                return this.MaxTenantsField;
            }
            set {
                if ((this.MaxTenantsField.Equals(value) != true)) {
                    this.MaxTenantsField = value;
                    this.RaisePropertyChanged("MaxTenants");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Plan {
            get {
                return this.PlanField;
            }
            set {
                if ((object.ReferenceEquals(this.PlanField, value) != true)) {
                    this.PlanField = value;
                    this.RaisePropertyChanged("Plan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TenantCount {
            get {
                return this.TenantCountField;
            }
            set {
                if ((this.TenantCountField.Equals(value) != true)) {
                    this.TenantCountField = value;
                    this.RaisePropertyChanged("TenantCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StoragePartition", Namespace="http://schemas.datacontract.org/2004/07/Sahara.Core.Settings.Models.Partitions")]
    [System.SerializableAttribute()]
    public partial class StoragePartition : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CDNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxTenantsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TenantCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CDN {
            get {
                return this.CDNField;
            }
            set {
                if ((object.ReferenceEquals(this.CDNField, value) != true)) {
                    this.CDNField = value;
                    this.RaisePropertyChanged("CDN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxTenants {
            get {
                return this.MaxTenantsField;
            }
            set {
                if ((this.MaxTenantsField.Equals(value) != true)) {
                    this.MaxTenantsField = value;
                    this.RaisePropertyChanged("MaxTenants");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TenantCount {
            get {
                return this.TenantCountField;
            }
            set {
                if ((this.TenantCountField.Equals(value) != true)) {
                    this.TenantCountField = value;
                    this.RaisePropertyChanged("TenantCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PlatformSettingsService.IPlatformSettingsService")]
    public interface IPlatformSettingsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlatformSettingsService/GetCorePlatformSettings", ReplyAction="http://tempuri.org/IPlatformSettingsService/GetCorePlatformSettingsResponse")]
        PlatformAdminSite.PlatformSettingsService.CorePlatformSettings GetCorePlatformSettings(string sharedClientKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlatformSettingsService/GetCorePlatformSettings", ReplyAction="http://tempuri.org/IPlatformSettingsService/GetCorePlatformSettingsResponse")]
        System.Threading.Tasks.Task<PlatformAdminSite.PlatformSettingsService.CorePlatformSettings> GetCorePlatformSettingsAsync(string sharedClientKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlatformSettingsService/GetCurrentEnvironment", ReplyAction="http://tempuri.org/IPlatformSettingsService/GetCurrentEnvironmentResponse")]
        string GetCurrentEnvironment();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlatformSettingsService/GetCurrentEnvironment", ReplyAction="http://tempuri.org/IPlatformSettingsService/GetCurrentEnvironmentResponse")]
        System.Threading.Tasks.Task<string> GetCurrentEnvironmentAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPlatformSettingsServiceChannel : PlatformAdminSite.PlatformSettingsService.IPlatformSettingsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlatformSettingsServiceClient : System.ServiceModel.ClientBase<PlatformAdminSite.PlatformSettingsService.IPlatformSettingsService>, PlatformAdminSite.PlatformSettingsService.IPlatformSettingsService {
        
        public PlatformSettingsServiceClient() {
        }
        
        public PlatformSettingsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlatformSettingsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlatformSettingsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlatformSettingsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PlatformAdminSite.PlatformSettingsService.CorePlatformSettings GetCorePlatformSettings(string sharedClientKey) {
            return base.Channel.GetCorePlatformSettings(sharedClientKey);
        }
        
        public System.Threading.Tasks.Task<PlatformAdminSite.PlatformSettingsService.CorePlatformSettings> GetCorePlatformSettingsAsync(string sharedClientKey) {
            return base.Channel.GetCorePlatformSettingsAsync(sharedClientKey);
        }
        
        public string GetCurrentEnvironment() {
            return base.Channel.GetCurrentEnvironment();
        }
        
        public System.Threading.Tasks.Task<string> GetCurrentEnvironmentAsync() {
            return base.Channel.GetCurrentEnvironmentAsync();
        }
    }
}
