//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlatformAdminSite.AccountCommerceService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequesterType", Namespace="http://schemas.datacontract.org/2004/07/Sahara.Core.Platform.Requests.Models")]
    public enum RequesterType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlatformUser = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccountUser = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Exempt = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataAccessResponseType", Namespace="http://schemas.datacontract.org/2004/07/Sahara.Core.Common.ResponseTypes")]
    [System.SerializableAttribute()]
    public partial class DataAccessResponseType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ErrorMessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoleInstanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuccessCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuccessMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] SuccessMessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isSuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ErrorMessages {
            get {
                return this.ErrorMessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessagesField, value) != true)) {
                    this.ErrorMessagesField = value;
                    this.RaisePropertyChanged("ErrorMessages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Results {
            get {
                return this.ResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultsField, value) != true)) {
                    this.ResultsField = value;
                    this.RaisePropertyChanged("Results");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoleInstance {
            get {
                return this.RoleInstanceField;
            }
            set {
                if ((this.RoleInstanceField.Equals(value) != true)) {
                    this.RoleInstanceField = value;
                    this.RaisePropertyChanged("RoleInstance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleName {
            get {
                return this.RoleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleNameField, value) != true)) {
                    this.RoleNameField = value;
                    this.RaisePropertyChanged("RoleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SuccessCode {
            get {
                return this.SuccessCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SuccessCodeField, value) != true)) {
                    this.SuccessCodeField = value;
                    this.RaisePropertyChanged("SuccessCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SuccessMessage {
            get {
                return this.SuccessMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.SuccessMessageField, value) != true)) {
                    this.SuccessMessageField = value;
                    this.RaisePropertyChanged("SuccessMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] SuccessMessages {
            get {
                return this.SuccessMessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.SuccessMessagesField, value) != true)) {
                    this.SuccessMessagesField = value;
                    this.RaisePropertyChanged("SuccessMessages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isSuccess {
            get {
                return this.isSuccessField;
            }
            set {
                if ((this.isSuccessField.Equals(value) != true)) {
                    this.isSuccessField = value;
                    this.RaisePropertyChanged("isSuccess");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccountCommerceService.IAccountCommerceService")]
    public interface IAccountCommerceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountCommerceService/GetDollarsToCreditsExchangeRate", ReplyAction="http://tempuri.org/IAccountCommerceService/GetDollarsToCreditsExchangeRateRespons" +
            "e")]
        int GetDollarsToCreditsExchangeRate(decimal dollarAmoun, string sharedClientKeyt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountCommerceService/GetDollarsToCreditsExchangeRate", ReplyAction="http://tempuri.org/IAccountCommerceService/GetDollarsToCreditsExchangeRateRespons" +
            "e")]
        System.Threading.Tasks.Task<int> GetDollarsToCreditsExchangeRateAsync(decimal dollarAmoun, string sharedClientKeyt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountCommerceService/GetCredits", ReplyAction="http://tempuri.org/IAccountCommerceService/GetCreditsResponse")]
        int GetCredits(string accountID, string sharedClientKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountCommerceService/GetCredits", ReplyAction="http://tempuri.org/IAccountCommerceService/GetCreditsResponse")]
        System.Threading.Tasks.Task<int> GetCreditsAsync(string accountID, string sharedClientKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountCommerceService/BuyCredits", ReplyAction="http://tempuri.org/IAccountCommerceService/BuyCreditsResponse")]
        PlatformAdminSite.AccountCommerceService.DataAccessResponseType BuyCredits(string accountID, decimal dollarAmount, string requesterId, PlatformAdminSite.AccountCommerceService.RequesterType requesterType, string ipAddress, string origin, string sharedClientKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountCommerceService/BuyCredits", ReplyAction="http://tempuri.org/IAccountCommerceService/BuyCreditsResponse")]
        System.Threading.Tasks.Task<PlatformAdminSite.AccountCommerceService.DataAccessResponseType> BuyCreditsAsync(string accountID, decimal dollarAmount, string requesterId, PlatformAdminSite.AccountCommerceService.RequesterType requesterType, string ipAddress, string origin, string sharedClientKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountCommerceService/SpendCredits", ReplyAction="http://tempuri.org/IAccountCommerceService/SpendCreditsResponse")]
        PlatformAdminSite.AccountCommerceService.DataAccessResponseType SpendCredits(string accountID, int creditAmount, string description, string requesterId, PlatformAdminSite.AccountCommerceService.RequesterType requesterType, string ipAddress, string origin, string sharedClientKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountCommerceService/SpendCredits", ReplyAction="http://tempuri.org/IAccountCommerceService/SpendCreditsResponse")]
        System.Threading.Tasks.Task<PlatformAdminSite.AccountCommerceService.DataAccessResponseType> SpendCreditsAsync(string accountID, int creditAmount, string description, string requesterId, PlatformAdminSite.AccountCommerceService.RequesterType requesterType, string ipAddress, string origin, string sharedClientKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountCommerceService/TradeCredits", ReplyAction="http://tempuri.org/IAccountCommerceService/TradeCreditsResponse")]
        PlatformAdminSite.AccountCommerceService.DataAccessResponseType TradeCredits(string fromAccountID, string toAccountID, int creditAmount, string description, string requesterId, PlatformAdminSite.AccountCommerceService.RequesterType requesterType, string ipAddress, string origin, string sharedClientKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountCommerceService/TradeCredits", ReplyAction="http://tempuri.org/IAccountCommerceService/TradeCreditsResponse")]
        System.Threading.Tasks.Task<PlatformAdminSite.AccountCommerceService.DataAccessResponseType> TradeCreditsAsync(string fromAccountID, string toAccountID, int creditAmount, string description, string requesterId, PlatformAdminSite.AccountCommerceService.RequesterType requesterType, string ipAddress, string origin, string sharedClientKey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccountCommerceServiceChannel : PlatformAdminSite.AccountCommerceService.IAccountCommerceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountCommerceServiceClient : System.ServiceModel.ClientBase<PlatformAdminSite.AccountCommerceService.IAccountCommerceService>, PlatformAdminSite.AccountCommerceService.IAccountCommerceService {
        
        public AccountCommerceServiceClient() {
        }
        
        public AccountCommerceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountCommerceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountCommerceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountCommerceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetDollarsToCreditsExchangeRate(decimal dollarAmoun, string sharedClientKeyt) {
            return base.Channel.GetDollarsToCreditsExchangeRate(dollarAmoun, sharedClientKeyt);
        }
        
        public System.Threading.Tasks.Task<int> GetDollarsToCreditsExchangeRateAsync(decimal dollarAmoun, string sharedClientKeyt) {
            return base.Channel.GetDollarsToCreditsExchangeRateAsync(dollarAmoun, sharedClientKeyt);
        }
        
        public int GetCredits(string accountID, string sharedClientKey) {
            return base.Channel.GetCredits(accountID, sharedClientKey);
        }
        
        public System.Threading.Tasks.Task<int> GetCreditsAsync(string accountID, string sharedClientKey) {
            return base.Channel.GetCreditsAsync(accountID, sharedClientKey);
        }
        
        public PlatformAdminSite.AccountCommerceService.DataAccessResponseType BuyCredits(string accountID, decimal dollarAmount, string requesterId, PlatformAdminSite.AccountCommerceService.RequesterType requesterType, string ipAddress, string origin, string sharedClientKey) {
            return base.Channel.BuyCredits(accountID, dollarAmount, requesterId, requesterType, ipAddress, origin, sharedClientKey);
        }
        
        public System.Threading.Tasks.Task<PlatformAdminSite.AccountCommerceService.DataAccessResponseType> BuyCreditsAsync(string accountID, decimal dollarAmount, string requesterId, PlatformAdminSite.AccountCommerceService.RequesterType requesterType, string ipAddress, string origin, string sharedClientKey) {
            return base.Channel.BuyCreditsAsync(accountID, dollarAmount, requesterId, requesterType, ipAddress, origin, sharedClientKey);
        }
        
        public PlatformAdminSite.AccountCommerceService.DataAccessResponseType SpendCredits(string accountID, int creditAmount, string description, string requesterId, PlatformAdminSite.AccountCommerceService.RequesterType requesterType, string ipAddress, string origin, string sharedClientKey) {
            return base.Channel.SpendCredits(accountID, creditAmount, description, requesterId, requesterType, ipAddress, origin, sharedClientKey);
        }
        
        public System.Threading.Tasks.Task<PlatformAdminSite.AccountCommerceService.DataAccessResponseType> SpendCreditsAsync(string accountID, int creditAmount, string description, string requesterId, PlatformAdminSite.AccountCommerceService.RequesterType requesterType, string ipAddress, string origin, string sharedClientKey) {
            return base.Channel.SpendCreditsAsync(accountID, creditAmount, description, requesterId, requesterType, ipAddress, origin, sharedClientKey);
        }
        
        public PlatformAdminSite.AccountCommerceService.DataAccessResponseType TradeCredits(string fromAccountID, string toAccountID, int creditAmount, string description, string requesterId, PlatformAdminSite.AccountCommerceService.RequesterType requesterType, string ipAddress, string origin, string sharedClientKey) {
            return base.Channel.TradeCredits(fromAccountID, toAccountID, creditAmount, description, requesterId, requesterType, ipAddress, origin, sharedClientKey);
        }
        
        public System.Threading.Tasks.Task<PlatformAdminSite.AccountCommerceService.DataAccessResponseType> TradeCreditsAsync(string fromAccountID, string toAccountID, int creditAmount, string description, string requesterId, PlatformAdminSite.AccountCommerceService.RequesterType requesterType, string ipAddress, string origin, string sharedClientKey) {
            return base.Channel.TradeCreditsAsync(fromAccountID, toAccountID, creditAmount, description, requesterId, requesterType, ipAddress, origin, sharedClientKey);
        }
    }
}
