//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlatformAdminSite.PlatformAuthenticationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationResponse", Namespace="http://schemas.datacontract.org/2004/07/WCF.WcfEndpoints.Contracts.Platform")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PlatformAdminSite.PlatformAuthenticationService.PlatformUser))]
    public partial class AuthenticationResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Security.Claims.ClaimsIdentity ClaimsIdentityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PlatformAdminSite.PlatformAuthenticationService.PlatformUser PlatformUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isSuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Security.Claims.ClaimsIdentity ClaimsIdentity {
            get {
                return this.ClaimsIdentityField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaimsIdentityField, value) != true)) {
                    this.ClaimsIdentityField = value;
                    this.RaisePropertyChanged("ClaimsIdentity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PlatformAdminSite.PlatformAuthenticationService.PlatformUser PlatformUser {
            get {
                return this.PlatformUserField;
            }
            set {
                if ((object.ReferenceEquals(this.PlatformUserField, value) != true)) {
                    this.PlatformUserField = value;
                    this.RaisePropertyChanged("PlatformUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isSuccess {
            get {
                return this.isSuccessField;
            }
            set {
                if ((this.isSuccessField.Equals(value) != true)) {
                    this.isSuccessField = value;
                    this.RaisePropertyChanged("isSuccess");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlatformUser", Namespace="http://schemas.datacontract.org/2004/07/Sahara.Core.Platform.Users.Models")]
    [System.SerializableAttribute()]
    public partial class PlatformUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Photo {
            get {
                return this.PhotoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoField, value) != true)) {
                    this.PhotoField = value;
                    this.RaisePropertyChanged("Photo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PlatformAuthenticationService.IPlatformAuthenticationService")]
    public interface IPlatformAuthenticationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlatformAuthenticationService/Authenticate", ReplyAction="http://tempuri.org/IPlatformAuthenticationService/AuthenticateResponse")]
        PlatformAdminSite.PlatformAuthenticationService.AuthenticationResponse Authenticate(string email, string password, string ipAddress, string origin, string sharedClientKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlatformAuthenticationService/Authenticate", ReplyAction="http://tempuri.org/IPlatformAuthenticationService/AuthenticateResponse")]
        System.Threading.Tasks.Task<PlatformAdminSite.PlatformAuthenticationService.AuthenticationResponse> AuthenticateAsync(string email, string password, string ipAddress, string origin, string sharedClientKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlatformAuthenticationService/GetClaimsIdentity", ReplyAction="http://tempuri.org/IPlatformAuthenticationService/GetClaimsIdentityResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlatformAdminSite.PlatformAuthenticationService.AuthenticationResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlatformAdminSite.PlatformAuthenticationService.PlatformUser))]
        System.Security.Claims.ClaimsIdentity GetClaimsIdentity(string userName, string sharedClientKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlatformAuthenticationService/GetClaimsIdentity", ReplyAction="http://tempuri.org/IPlatformAuthenticationService/GetClaimsIdentityResponse")]
        System.Threading.Tasks.Task<System.Security.Claims.ClaimsIdentity> GetClaimsIdentityAsync(string userName, string sharedClientKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlatformAuthenticationService/Logout", ReplyAction="http://tempuri.org/IPlatformAuthenticationService/LogoutResponse")]
        void Logout(string userName, string sharedClientKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlatformAuthenticationService/Logout", ReplyAction="http://tempuri.org/IPlatformAuthenticationService/LogoutResponse")]
        System.Threading.Tasks.Task LogoutAsync(string userName, string sharedClientKey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPlatformAuthenticationServiceChannel : PlatformAdminSite.PlatformAuthenticationService.IPlatformAuthenticationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlatformAuthenticationServiceClient : System.ServiceModel.ClientBase<PlatformAdminSite.PlatformAuthenticationService.IPlatformAuthenticationService>, PlatformAdminSite.PlatformAuthenticationService.IPlatformAuthenticationService {
        
        public PlatformAuthenticationServiceClient() {
        }
        
        public PlatformAuthenticationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlatformAuthenticationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlatformAuthenticationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlatformAuthenticationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PlatformAdminSite.PlatformAuthenticationService.AuthenticationResponse Authenticate(string email, string password, string ipAddress, string origin, string sharedClientKey) {
            return base.Channel.Authenticate(email, password, ipAddress, origin, sharedClientKey);
        }
        
        public System.Threading.Tasks.Task<PlatformAdminSite.PlatformAuthenticationService.AuthenticationResponse> AuthenticateAsync(string email, string password, string ipAddress, string origin, string sharedClientKey) {
            return base.Channel.AuthenticateAsync(email, password, ipAddress, origin, sharedClientKey);
        }
        
        public System.Security.Claims.ClaimsIdentity GetClaimsIdentity(string userName, string sharedClientKey) {
            return base.Channel.GetClaimsIdentity(userName, sharedClientKey);
        }
        
        public System.Threading.Tasks.Task<System.Security.Claims.ClaimsIdentity> GetClaimsIdentityAsync(string userName, string sharedClientKey) {
            return base.Channel.GetClaimsIdentityAsync(userName, sharedClientKey);
        }
        
        public void Logout(string userName, string sharedClientKey) {
            base.Channel.Logout(userName, sharedClientKey);
        }
        
        public System.Threading.Tasks.Task LogoutAsync(string userName, string sharedClientKey) {
            return base.Channel.LogoutAsync(userName, sharedClientKey);
        }
    }
}
