//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlatformAdminSite.AccountRegistrationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegisterNewAccountModel", Namespace="http://schemas.datacontract.org/2004/07/Sahara.Core.Accounts.Registration.Models")]
    [System.SerializableAttribute()]
    public partial class RegisterNewAccountModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConfirmPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountName {
            get {
                return this.AccountNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNameField, value) != true)) {
                    this.AccountNameField = value;
                    this.RaisePropertyChanged("AccountName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConfirmPassword {
            get {
                return this.ConfirmPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfirmPasswordField, value) != true)) {
                    this.ConfirmPasswordField = value;
                    this.RaisePropertyChanged("ConfirmPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Origin {
            get {
                return this.OriginField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginField, value) != true)) {
                    this.OriginField = value;
                    this.RaisePropertyChanged("Origin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataAccessResponseType", Namespace="http://schemas.datacontract.org/2004/07/Sahara.Core.Common.ResponseTypes")]
    [System.SerializableAttribute()]
    public partial class DataAccessResponseType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ErrorMessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoleInstanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuccessCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuccessMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] SuccessMessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isSuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ErrorMessages {
            get {
                return this.ErrorMessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessagesField, value) != true)) {
                    this.ErrorMessagesField = value;
                    this.RaisePropertyChanged("ErrorMessages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Results {
            get {
                return this.ResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultsField, value) != true)) {
                    this.ResultsField = value;
                    this.RaisePropertyChanged("Results");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoleInstance {
            get {
                return this.RoleInstanceField;
            }
            set {
                if ((this.RoleInstanceField.Equals(value) != true)) {
                    this.RoleInstanceField = value;
                    this.RaisePropertyChanged("RoleInstance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleName {
            get {
                return this.RoleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleNameField, value) != true)) {
                    this.RoleNameField = value;
                    this.RaisePropertyChanged("RoleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SuccessCode {
            get {
                return this.SuccessCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SuccessCodeField, value) != true)) {
                    this.SuccessCodeField = value;
                    this.RaisePropertyChanged("SuccessCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SuccessMessage {
            get {
                return this.SuccessMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.SuccessMessageField, value) != true)) {
                    this.SuccessMessageField = value;
                    this.RaisePropertyChanged("SuccessMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] SuccessMessages {
            get {
                return this.SuccessMessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.SuccessMessagesField, value) != true)) {
                    this.SuccessMessagesField = value;
                    this.RaisePropertyChanged("SuccessMessages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isSuccess {
            get {
                return this.isSuccessField;
            }
            set {
                if ((this.isSuccessField.Equals(value) != true)) {
                    this.isSuccessField = value;
                    this.RaisePropertyChanged("isSuccess");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationResponseType", Namespace="http://schemas.datacontract.org/2004/07/Sahara.Core.Common.Validation.ResponseTyp" +
        "es")]
    [System.SerializableAttribute()]
    public partial class ValidationResponseType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isValidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string validationMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isValid {
            get {
                return this.isValidField;
            }
            set {
                if ((this.isValidField.Equals(value) != true)) {
                    this.isValidField = value;
                    this.RaisePropertyChanged("isValid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string validationMessage {
            get {
                return this.validationMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.validationMessageField, value) != true)) {
                    this.validationMessageField = value;
                    this.RaisePropertyChanged("validationMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequesterType", Namespace="http://schemas.datacontract.org/2004/07/Sahara.Core.Platform.Requests.Models")]
    public enum RequesterType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlatformUser = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccountUser = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Exempt = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccountRegistrationService.IAccountRegistrationService")]
    public interface IAccountRegistrationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountRegistrationService/RegisterAccount", ReplyAction="http://tempuri.org/IAccountRegistrationService/RegisterAccountResponse")]
        PlatformAdminSite.AccountRegistrationService.DataAccessResponseType RegisterAccount(PlatformAdminSite.AccountRegistrationService.RegisterNewAccountModel registerNewAccountModel, string sharedClientKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountRegistrationService/RegisterAccount", ReplyAction="http://tempuri.org/IAccountRegistrationService/RegisterAccountResponse")]
        System.Threading.Tasks.Task<PlatformAdminSite.AccountRegistrationService.DataAccessResponseType> RegisterAccountAsync(PlatformAdminSite.AccountRegistrationService.RegisterNewAccountModel registerNewAccountModel, string sharedClientKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountRegistrationService/ValidateAccountName", ReplyAction="http://tempuri.org/IAccountRegistrationService/ValidateAccountNameResponse")]
        PlatformAdminSite.AccountRegistrationService.ValidationResponseType ValidateAccountName(string AccountName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountRegistrationService/ValidateAccountName", ReplyAction="http://tempuri.org/IAccountRegistrationService/ValidateAccountNameResponse")]
        System.Threading.Tasks.Task<PlatformAdminSite.AccountRegistrationService.ValidationResponseType> ValidateAccountNameAsync(string AccountName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountRegistrationService/ValidateEmail", ReplyAction="http://tempuri.org/IAccountRegistrationService/ValidateEmailResponse")]
        PlatformAdminSite.AccountRegistrationService.ValidationResponseType ValidateEmail(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountRegistrationService/ValidateEmail", ReplyAction="http://tempuri.org/IAccountRegistrationService/ValidateEmailResponse")]
        System.Threading.Tasks.Task<PlatformAdminSite.AccountRegistrationService.ValidationResponseType> ValidateEmailAsync(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountRegistrationService/ValidatePhoneNumber", ReplyAction="http://tempuri.org/IAccountRegistrationService/ValidatePhoneNumberResponse")]
        PlatformAdminSite.AccountRegistrationService.ValidationResponseType ValidatePhoneNumber(string PhoneNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountRegistrationService/ValidatePhoneNumber", ReplyAction="http://tempuri.org/IAccountRegistrationService/ValidatePhoneNumberResponse")]
        System.Threading.Tasks.Task<PlatformAdminSite.AccountRegistrationService.ValidationResponseType> ValidatePhoneNumberAsync(string PhoneNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountRegistrationService/ValidateFirstName", ReplyAction="http://tempuri.org/IAccountRegistrationService/ValidateFirstNameResponse")]
        PlatformAdminSite.AccountRegistrationService.ValidationResponseType ValidateFirstName(string FirstName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountRegistrationService/ValidateFirstName", ReplyAction="http://tempuri.org/IAccountRegistrationService/ValidateFirstNameResponse")]
        System.Threading.Tasks.Task<PlatformAdminSite.AccountRegistrationService.ValidationResponseType> ValidateFirstNameAsync(string FirstName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountRegistrationService/ValidateLastName", ReplyAction="http://tempuri.org/IAccountRegistrationService/ValidateLastNameResponse")]
        PlatformAdminSite.AccountRegistrationService.ValidationResponseType ValidateLastName(string LastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountRegistrationService/ValidateLastName", ReplyAction="http://tempuri.org/IAccountRegistrationService/ValidateLastNameResponse")]
        System.Threading.Tasks.Task<PlatformAdminSite.AccountRegistrationService.ValidationResponseType> ValidateLastNameAsync(string LastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountRegistrationService/ProvisionAccount", ReplyAction="http://tempuri.org/IAccountRegistrationService/ProvisionAccountResponse")]
        PlatformAdminSite.AccountRegistrationService.DataAccessResponseType ProvisionAccount(string accountId, string requesterId, PlatformAdminSite.AccountRegistrationService.RequesterType requesterType, string sharedClientKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountRegistrationService/ProvisionAccount", ReplyAction="http://tempuri.org/IAccountRegistrationService/ProvisionAccountResponse")]
        System.Threading.Tasks.Task<PlatformAdminSite.AccountRegistrationService.DataAccessResponseType> ProvisionAccountAsync(string accountId, string requesterId, PlatformAdminSite.AccountRegistrationService.RequesterType requesterType, string sharedClientKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountRegistrationService/ConvertToAccountNameKey", ReplyAction="http://tempuri.org/IAccountRegistrationService/ConvertToAccountNameKeyResponse")]
        string ConvertToAccountNameKey(string AccountName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountRegistrationService/ConvertToAccountNameKey", ReplyAction="http://tempuri.org/IAccountRegistrationService/ConvertToAccountNameKeyResponse")]
        System.Threading.Tasks.Task<string> ConvertToAccountNameKeyAsync(string AccountName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccountRegistrationServiceChannel : PlatformAdminSite.AccountRegistrationService.IAccountRegistrationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountRegistrationServiceClient : System.ServiceModel.ClientBase<PlatformAdminSite.AccountRegistrationService.IAccountRegistrationService>, PlatformAdminSite.AccountRegistrationService.IAccountRegistrationService {
        
        public AccountRegistrationServiceClient() {
        }
        
        public AccountRegistrationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountRegistrationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountRegistrationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountRegistrationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PlatformAdminSite.AccountRegistrationService.DataAccessResponseType RegisterAccount(PlatformAdminSite.AccountRegistrationService.RegisterNewAccountModel registerNewAccountModel, string sharedClientKey) {
            return base.Channel.RegisterAccount(registerNewAccountModel, sharedClientKey);
        }
        
        public System.Threading.Tasks.Task<PlatformAdminSite.AccountRegistrationService.DataAccessResponseType> RegisterAccountAsync(PlatformAdminSite.AccountRegistrationService.RegisterNewAccountModel registerNewAccountModel, string sharedClientKey) {
            return base.Channel.RegisterAccountAsync(registerNewAccountModel, sharedClientKey);
        }
        
        public PlatformAdminSite.AccountRegistrationService.ValidationResponseType ValidateAccountName(string AccountName) {
            return base.Channel.ValidateAccountName(AccountName);
        }
        
        public System.Threading.Tasks.Task<PlatformAdminSite.AccountRegistrationService.ValidationResponseType> ValidateAccountNameAsync(string AccountName) {
            return base.Channel.ValidateAccountNameAsync(AccountName);
        }
        
        public PlatformAdminSite.AccountRegistrationService.ValidationResponseType ValidateEmail(string Email) {
            return base.Channel.ValidateEmail(Email);
        }
        
        public System.Threading.Tasks.Task<PlatformAdminSite.AccountRegistrationService.ValidationResponseType> ValidateEmailAsync(string Email) {
            return base.Channel.ValidateEmailAsync(Email);
        }
        
        public PlatformAdminSite.AccountRegistrationService.ValidationResponseType ValidatePhoneNumber(string PhoneNumber) {
            return base.Channel.ValidatePhoneNumber(PhoneNumber);
        }
        
        public System.Threading.Tasks.Task<PlatformAdminSite.AccountRegistrationService.ValidationResponseType> ValidatePhoneNumberAsync(string PhoneNumber) {
            return base.Channel.ValidatePhoneNumberAsync(PhoneNumber);
        }
        
        public PlatformAdminSite.AccountRegistrationService.ValidationResponseType ValidateFirstName(string FirstName) {
            return base.Channel.ValidateFirstName(FirstName);
        }
        
        public System.Threading.Tasks.Task<PlatformAdminSite.AccountRegistrationService.ValidationResponseType> ValidateFirstNameAsync(string FirstName) {
            return base.Channel.ValidateFirstNameAsync(FirstName);
        }
        
        public PlatformAdminSite.AccountRegistrationService.ValidationResponseType ValidateLastName(string LastName) {
            return base.Channel.ValidateLastName(LastName);
        }
        
        public System.Threading.Tasks.Task<PlatformAdminSite.AccountRegistrationService.ValidationResponseType> ValidateLastNameAsync(string LastName) {
            return base.Channel.ValidateLastNameAsync(LastName);
        }
        
        public PlatformAdminSite.AccountRegistrationService.DataAccessResponseType ProvisionAccount(string accountId, string requesterId, PlatformAdminSite.AccountRegistrationService.RequesterType requesterType, string sharedClientKey) {
            return base.Channel.ProvisionAccount(accountId, requesterId, requesterType, sharedClientKey);
        }
        
        public System.Threading.Tasks.Task<PlatformAdminSite.AccountRegistrationService.DataAccessResponseType> ProvisionAccountAsync(string accountId, string requesterId, PlatformAdminSite.AccountRegistrationService.RequesterType requesterType, string sharedClientKey) {
            return base.Channel.ProvisionAccountAsync(accountId, requesterId, requesterType, sharedClientKey);
        }
        
        public string ConvertToAccountNameKey(string AccountName) {
            return base.Channel.ConvertToAccountNameKey(AccountName);
        }
        
        public System.Threading.Tasks.Task<string> ConvertToAccountNameKeyAsync(string AccountName) {
            return base.Channel.ConvertToAccountNameKeyAsync(AccountName);
        }
    }
}
