INSERT INTO PaymentFrequencies

(PaymentFrequencyMonths, PaymentFrequencyName, Interval, IntervalCount, PriceBreak)

--  PaymentFrequencyMonths/ID   Name       Interval   IntervalCount    Price Break

SELECT					'0',	'None',		'None',		'0',			'0'
UNION ALL

SELECT					'1',	'Monthly',	'Month',	'1',			'0'
UNION ALL

SELECT					'12',	'Yearly',	'Year',		'1',			'.10' -- Save 10% on yearly plans! (THIS IS HARD CODED INTO subscribe.[Config_Domain].com/sub so update in BOTH places!!!!!


-- **Note** Yearly plans wth IntervalCount of 1 are the maximum available on Stripe, If weeks are required, some refactoring of business logic will be needed as all UI's and parts of CoreServices use the PaymentFrequencyMonths integer to calculate plan costs and discounts. 
-- **Note** PaymentPlans have a MonthlyRate property that is used to calculate against these frequencies. If week-based intervals are required, some refactoring will need to occur.
-- **Note** When a new plan is created (or generated by platform initialization) the associated Stripe PlanId's are generated via the Sahara.Core.Common.Methods.PaymentPlans class. Concatinating 'IntervalCount' + 'Interval' with lowered casing and replacing white spaces with "-" (for each plan/frequency variation).
